server:
  port: 8888
  servlet:
    context-path: /cboard
spring:
  datasource:
    schema: classpath:h2-demo/h2.sql
    data: classpath:h2-demo/sample_data.sql
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/H2Data/cboard;AUTO_SERVER=TRUE;LOG=0;UNDO_LOG=0
    username: sa
    password:
    name: cboard
  h2:
    console:
      enabled: true
      path: /h2
  servlet:
    multipart:
      max-file-size: 10485760 #10M
      max-request-size: 10485760
  freemarker:
    cache: false
    charset: UTF-8
    suffix: .ftl
    content-type: text/html
    template-loader-path: classpath:/templates/config/

log:
  negativeFilter: List\\.do
  positveFilter:
dataprovider:
  resultLimit: 1000000
mail:
  smtp:
    host: 127.0.0.1
    port: 8825
    from: test@test.com
#    username:
#    password:
#    ssl:
#      checkserveridentity: false
#      startTLSEnabled: false
admin_user_id: 1
phantomjs_path: D:/Program Files/phantomjs-2.1.1/bin/phantomjs.exe
